# Generated by Django 5.1.1 on 2024-11-07 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_permission_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['id']},
        ),
    ]
